# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: '2'
services:
  firefox:
    image: selenium/node-firefox:3.141.59-titanium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      NODE_MAX_SESSION: 5
      NODE_MAX_INSTANCES: 5
      HUB_HOST: hub

  chrome:
    image: selenium/node-chrome:3.141.59-titanium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      NODE_MAX_SESSION: 5
      NODE_MAX_INSTANCES: 5
      HUB_HOST: hub

  hub:
    image: selenium/hub:3.141.59-titanium
    ports:
      - "4444:4444"
    environment:
      GRID_MAX_SESSION: 5